import{a as q,i,S as E}from"./assets/vendor-BDaiwwc1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const P="36828323-5d4b30a68db3a86c330ff5a61",R="https://pixabay.com/api/";async function y(r,e){try{const o=await q.get(R,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:e}});return o.data.hits.length===0&&i.error({message:"Sorry, there are no images matching your search query.",position:"topRight"}),{result:o.data.hits,totalHits:o.data.totalHits}}catch(o){i.error({title:"Error",message:"Something went wrong. Try again later",position:"topRight"}),console.error("Error: ",o)}}let d;function w(r){return r.map(e=>{let{largeImageURL:o,webformatURL:s,tags:t,likes:a,views:c,comments:S,downloads:b}=e;return`
      <a href="${o}" class="photo-card">
        <img src="${s}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${a}</p>
          <p><strong>Views:</strong> ${c}</p>
          <p><strong>Comments:</strong> ${S}</p>
          <p><strong>Downloads:</strong> ${b}</p>
        </div>
      </a>
    `}).join("")}function L(){d?d.refresh():d=new E(".gallery a",{captionsData:"alt",captionDelay:150,animationSpeed:200,closeText:"×",navText:["<",">"]})}const f=document.querySelector(".search-form"),g=document.querySelector(".gallery"),p=document.querySelector(".loader-wrapper"),h=document.querySelector(".search-form input"),l=document.querySelector(".load-more"),n={query:"",page:1,total:null};f.addEventListener("submit",async r=>{if(r.preventDefault(),n.query=r.target.elements.searchQuery.value,n.page=1,!n.query){i.warning({message:"Please enter a search query",position:"topRight"});return}g.innerHTML="",m(p),h.classList.add("active");try{const{result:e,totalHits:o}=await y(n.query,n.page);if(e.length===0){u(l);return}const s=w(e);g.innerHTML=s,n.total=o,L(),v()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{f.searchQuery.value="",u(p),h.classList.remove("active")}});l.addEventListener("click",async r=>{m(p);try{u(l),n.page+=1;const{result:e}=await y(n.query,n.page),o=w(e);g.insertAdjacentHTML("beforeend",o),v(),L(),x()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{u(p)}});function v(){const e=Math.ceil(n.total/40);n.page>=e?(u(l),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m(l)}function m(r){r.classList.remove("hidden")}function u(r){r.classList.add("hidden")}function x(){const e=g.firstElementChild.getBoundingClientRect().height*2;window.scrollBy({behavior:"smooth",top:e})}
//# sourceMappingURL=index.js.map
