import{a as b,i as n,S as E}from"./assets/vendor-BDaiwwc1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const P="36828323-5d4b30a68db3a86c330ff5a61",R="https://pixabay.com/api/";async function y(r,e){try{const o=await b.get(R,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:e}});return o.data.hits.length===0&&n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),{result:o.data.hits,totalHits:o.data.totalHits}}catch(o){n.error({title:"Error",message:"Something went wrong. Try again later",position:"topRight"}),console.error("Error: ",o)}}let u;function L(r){return r.map(e=>{let{largeImageURL:o,webformatURL:i,tags:t,likes:a,views:c,comments:S,downloads:q}=e;return`
      <a href="${o}" class="photo-card">
        <img src="${i}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${a}</p>
          <p><strong>Views:</strong> ${c}</p>
          <p><strong>Comments:</strong> ${S}</p>
          <p><strong>Downloads:</strong> ${q}</p>
        </div>
      </a>
    `}).join("")}function w(){u?u.refresh():u=new E(".gallery a",{captionsData:"alt",captionDelay:150,animationSpeed:200,closeText:"×",navText:["<",">"]})}const f=document.querySelector(".search-form"),g=document.querySelector(".gallery"),l=document.querySelector(".loader-wrapper"),h=document.querySelector(".search-form input"),p=document.querySelector(".load-more"),s={query:"",page:1,total:null};f.addEventListener("submit",async r=>{if(r.preventDefault(),s.query=r.target.elements.searchQuery.value,s.page=1,!s.query){n.warning({message:"Please enter a search query",position:"topRight"});return}g.innerHTML="",d(l),h.classList.add("active");try{const{result:e,totalHits:o}=await y(s.query,s.page);if(e.length===0){n.info({message:"Sorry, there are no images matching your search query",position:"topRight"});return}const i=L(e);g.innerHTML=i,s.total=o,w(),v()}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{f.searchQuery.value="",m(l),h.classList.remove("active")}});p.addEventListener("click",async r=>{d(l);try{s.page+=1,v();const{result:e}=await y(s.query,s.page),o=L(e);g.insertAdjacentHTML("beforeend",o),w()}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{m(l)}});function v(){const e=Math.ceil(s.total/40);s.page>=e?(m(p),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d(p)}function d(r){r.classList.remove("hidden")}function m(r){r.classList.add("hidden")}
//# sourceMappingURL=index.js.map
